{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: windmill
  template:
    metadata:
      labels: 
        app: windmill
        container: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
        - name: "POSTGRES_PASSWORD"
          value: "{{ .Values.postgres.password }}"
        - name: "POSTGRES_DB"
          value: "{{ .Values.postgres.dbName }}"
        volumeMounts:
          - mountPath: "/var/lib/postgresql"
            name: task-pv-storage
  volumeClaimTemplates:
  - metadata:
      name: task-pv-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10G

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: windmill
    container: postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- else }}

{{- end }}
